/**
 * @fileoverview gRPC-Web generated client stub for org.example.common_grpc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: AvailabilityService.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.org = {};
proto.org.example = {};
proto.org.example.common_grpc = require('./AvailabilityService_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.org.example.common_grpc.AvailabilityServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.org.example.common_grpc.AvailabilityServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.common_grpc.OfferSearchRequest,
 *   !proto.org.example.common_grpc.AvailableOffersResponse>}
 */
const methodDescriptor_AvailabilityService_GetAvailableOffersForHotel = new grpc.web.MethodDescriptor(
  '/org.example.common_grpc.AvailabilityService/GetAvailableOffersForHotel',
  grpc.web.MethodType.UNARY,
  proto.org.example.common_grpc.OfferSearchRequest,
  proto.org.example.common_grpc.AvailableOffersResponse,
  /**
   * @param {!proto.org.example.common_grpc.OfferSearchRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.common_grpc.AvailableOffersResponse.deserializeBinary
);


/**
 * @param {!proto.org.example.common_grpc.OfferSearchRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.common_grpc.AvailableOffersResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.common_grpc.AvailableOffersResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.common_grpc.AvailabilityServiceClient.prototype.getAvailableOffersForHotel =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.common_grpc.AvailabilityService/GetAvailableOffersForHotel',
      request,
      metadata || {},
      methodDescriptor_AvailabilityService_GetAvailableOffersForHotel,
      callback);
};


/**
 * @param {!proto.org.example.common_grpc.OfferSearchRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.common_grpc.AvailableOffersResponse>}
 *     Promise that resolves to the response
 */
proto.org.example.common_grpc.AvailabilityServicePromiseClient.prototype.getAvailableOffersForHotel =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.common_grpc.AvailabilityService/GetAvailableOffersForHotel',
      request,
      metadata || {},
      methodDescriptor_AvailabilityService_GetAvailableOffersForHotel);
};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.org.example.common_grpc.AgencyOfferServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.org.example.common_grpc.AgencyOfferServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.org.example.common_grpc.AgencyOfferRequest,
 *   !proto.org.example.common_grpc.AgencyOfferResponse>}
 */
const methodDescriptor_AgencyOfferService_GetOffersForAgency = new grpc.web.MethodDescriptor(
  '/org.example.common_grpc.AgencyOfferService/GetOffersForAgency',
  grpc.web.MethodType.UNARY,
  proto.org.example.common_grpc.AgencyOfferRequest,
  proto.org.example.common_grpc.AgencyOfferResponse,
  /**
   * @param {!proto.org.example.common_grpc.AgencyOfferRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.org.example.common_grpc.AgencyOfferResponse.deserializeBinary
);


/**
 * @param {!proto.org.example.common_grpc.AgencyOfferRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.org.example.common_grpc.AgencyOfferResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.org.example.common_grpc.AgencyOfferResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.org.example.common_grpc.AgencyOfferServiceClient.prototype.getOffersForAgency =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/org.example.common_grpc.AgencyOfferService/GetOffersForAgency',
      request,
      metadata || {},
      methodDescriptor_AgencyOfferService_GetOffersForAgency,
      callback);
};


/**
 * @param {!proto.org.example.common_grpc.AgencyOfferRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.org.example.common_grpc.AgencyOfferResponse>}
 *     Promise that resolves to the response
 */
proto.org.example.common_grpc.AgencyOfferServicePromiseClient.prototype.getOffersForAgency =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/org.example.common_grpc.AgencyOfferService/GetOffersForAgency',
      request,
      metadata || {},
      methodDescriptor_AgencyOfferService_GetOffersForAgency);
};


module.exports = proto.org.example.common_grpc;

