// source: AvailabilityService.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.org.example.common_grpc.AgencyOfferRequest', null, global);
goog.exportSymbol('proto.org.example.common_grpc.AgencyOfferResponse', null, global);
goog.exportSymbol('proto.org.example.common_grpc.AvailableOffersResponse', null, global);
goog.exportSymbol('proto.org.example.common_grpc.OfferDTO', null, global);
goog.exportSymbol('proto.org.example.common_grpc.OfferSearchRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.org.example.common_grpc.OfferSearchRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.org.example.common_grpc.OfferSearchRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.org.example.common_grpc.OfferSearchRequest.displayName = 'proto.org.example.common_grpc.OfferSearchRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.org.example.common_grpc.AvailableOffersResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.org.example.common_grpc.AvailableOffersResponse.repeatedFields_, null);
};
goog.inherits(proto.org.example.common_grpc.AvailableOffersResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.org.example.common_grpc.AvailableOffersResponse.displayName = 'proto.org.example.common_grpc.AvailableOffersResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.org.example.common_grpc.OfferDTO = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.org.example.common_grpc.OfferDTO.repeatedFields_, null);
};
goog.inherits(proto.org.example.common_grpc.OfferDTO, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.org.example.common_grpc.OfferDTO.displayName = 'proto.org.example.common_grpc.OfferDTO';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.org.example.common_grpc.AgencyOfferRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.org.example.common_grpc.AgencyOfferRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.org.example.common_grpc.AgencyOfferRequest.displayName = 'proto.org.example.common_grpc.AgencyOfferRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.org.example.common_grpc.AgencyOfferResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.org.example.common_grpc.AgencyOfferResponse.repeatedFields_, null);
};
goog.inherits(proto.org.example.common_grpc.AgencyOfferResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.org.example.common_grpc.AgencyOfferResponse.displayName = 'proto.org.example.common_grpc.AgencyOfferResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.org.example.common_grpc.OfferSearchRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.org.example.common_grpc.OfferSearchRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.example.common_grpc.OfferSearchRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    agencylogin: jspb.Message.getFieldWithDefault(msg, 1, ""),
    agencypassword: jspb.Message.getFieldWithDefault(msg, 2, ""),
    hotelid: jspb.Message.getFieldWithDefault(msg, 3, 0),
    city: jspb.Message.getFieldWithDefault(msg, 4, ""),
    stars: jspb.Message.getFieldWithDefault(msg, 5, 0),
    category: jspb.Message.getFieldWithDefault(msg, 6, ""),
    capacity: jspb.Message.getFieldWithDefault(msg, 7, 0),
    start: jspb.Message.getFieldWithDefault(msg, 8, ""),
    end: jspb.Message.getFieldWithDefault(msg, 9, ""),
    maxprice: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.org.example.common_grpc.OfferSearchRequest}
 */
proto.org.example.common_grpc.OfferSearchRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.org.example.common_grpc.OfferSearchRequest;
  return proto.org.example.common_grpc.OfferSearchRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.org.example.common_grpc.OfferSearchRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.org.example.common_grpc.OfferSearchRequest}
 */
proto.org.example.common_grpc.OfferSearchRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAgencylogin(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAgencypassword(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHotelid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCity(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStars(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategory(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCapacity(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setStart(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setEnd(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMaxprice(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.org.example.common_grpc.OfferSearchRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.org.example.common_grpc.OfferSearchRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.example.common_grpc.OfferSearchRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAgencylogin();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAgencypassword();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getHotelid();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getCity();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getStars();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getCategory();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCapacity();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getStart();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getEnd();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getMaxprice();
  if (f !== 0.0) {
    writer.writeDouble(
      10,
      f
    );
  }
};


/**
 * optional string agencyLogin = 1;
 * @return {string}
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.getAgencylogin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.org.example.common_grpc.OfferSearchRequest} returns this
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.setAgencylogin = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string agencyPassword = 2;
 * @return {string}
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.getAgencypassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.org.example.common_grpc.OfferSearchRequest} returns this
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.setAgencypassword = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 hotelId = 3;
 * @return {number}
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.getHotelid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.org.example.common_grpc.OfferSearchRequest} returns this
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.setHotelid = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string city = 4;
 * @return {string}
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.getCity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.org.example.common_grpc.OfferSearchRequest} returns this
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.setCity = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 stars = 5;
 * @return {number}
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.getStars = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.org.example.common_grpc.OfferSearchRequest} returns this
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.setStars = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string category = 6;
 * @return {string}
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.getCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.org.example.common_grpc.OfferSearchRequest} returns this
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.setCategory = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int32 capacity = 7;
 * @return {number}
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.getCapacity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.org.example.common_grpc.OfferSearchRequest} returns this
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.setCapacity = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional string start = 8;
 * @return {string}
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.getStart = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.org.example.common_grpc.OfferSearchRequest} returns this
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.setStart = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string end = 9;
 * @return {string}
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.getEnd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.org.example.common_grpc.OfferSearchRequest} returns this
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.setEnd = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional double maxPrice = 10;
 * @return {number}
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.getMaxprice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.org.example.common_grpc.OfferSearchRequest} returns this
 */
proto.org.example.common_grpc.OfferSearchRequest.prototype.setMaxprice = function(value) {
  return jspb.Message.setProto3FloatField(this, 10, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.org.example.common_grpc.AvailableOffersResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.org.example.common_grpc.AvailableOffersResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.org.example.common_grpc.AvailableOffersResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.org.example.common_grpc.AvailableOffersResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.example.common_grpc.AvailableOffersResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    offersList: jspb.Message.toObjectList(msg.getOffersList(),
    proto.org.example.common_grpc.OfferDTO.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.org.example.common_grpc.AvailableOffersResponse}
 */
proto.org.example.common_grpc.AvailableOffersResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.org.example.common_grpc.AvailableOffersResponse;
  return proto.org.example.common_grpc.AvailableOffersResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.org.example.common_grpc.AvailableOffersResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.org.example.common_grpc.AvailableOffersResponse}
 */
proto.org.example.common_grpc.AvailableOffersResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.org.example.common_grpc.OfferDTO;
      reader.readMessage(value,proto.org.example.common_grpc.OfferDTO.deserializeBinaryFromReader);
      msg.addOffers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.org.example.common_grpc.AvailableOffersResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.org.example.common_grpc.AvailableOffersResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.org.example.common_grpc.AvailableOffersResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.example.common_grpc.AvailableOffersResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOffersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.org.example.common_grpc.OfferDTO.serializeBinaryToWriter
    );
  }
};


/**
 * repeated OfferDTO offers = 1;
 * @return {!Array<!proto.org.example.common_grpc.OfferDTO>}
 */
proto.org.example.common_grpc.AvailableOffersResponse.prototype.getOffersList = function() {
  return /** @type{!Array<!proto.org.example.common_grpc.OfferDTO>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.org.example.common_grpc.OfferDTO, 1));
};


/**
 * @param {!Array<!proto.org.example.common_grpc.OfferDTO>} value
 * @return {!proto.org.example.common_grpc.AvailableOffersResponse} returns this
*/
proto.org.example.common_grpc.AvailableOffersResponse.prototype.setOffersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.org.example.common_grpc.OfferDTO=} opt_value
 * @param {number=} opt_index
 * @return {!proto.org.example.common_grpc.OfferDTO}
 */
proto.org.example.common_grpc.AvailableOffersResponse.prototype.addOffers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.org.example.common_grpc.OfferDTO, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.org.example.common_grpc.AvailableOffersResponse} returns this
 */
proto.org.example.common_grpc.AvailableOffersResponse.prototype.clearOffersList = function() {
  return this.setOffersList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.org.example.common_grpc.OfferDTO.repeatedFields_ = [11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.org.example.common_grpc.OfferDTO.prototype.toObject = function(opt_includeInstance) {
  return proto.org.example.common_grpc.OfferDTO.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.org.example.common_grpc.OfferDTO} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.example.common_grpc.OfferDTO.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    hotelid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    hotelname: jspb.Message.getFieldWithDefault(msg, 3, ""),
    hotelstars: jspb.Message.getFieldWithDefault(msg, 4, 0),
    roomid: jspb.Message.getFieldWithDefault(msg, 5, 0),
    agencyid: jspb.Message.getFieldWithDefault(msg, 6, 0),
    agencyname: jspb.Message.getFieldWithDefault(msg, 7, ""),
    capacity: jspb.Message.getFieldWithDefault(msg, 8, 0),
    percentage: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0),
    newprice: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 0.0),
    roomimageurlsList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.org.example.common_grpc.OfferDTO}
 */
proto.org.example.common_grpc.OfferDTO.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.org.example.common_grpc.OfferDTO;
  return proto.org.example.common_grpc.OfferDTO.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.org.example.common_grpc.OfferDTO} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.org.example.common_grpc.OfferDTO}
 */
proto.org.example.common_grpc.OfferDTO.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHotelid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setHotelname(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHotelstars(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRoomid(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAgencyid(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setAgencyname(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCapacity(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPercentage(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setNewprice(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addRoomimageurls(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.org.example.common_grpc.OfferDTO.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.org.example.common_grpc.OfferDTO.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.org.example.common_grpc.OfferDTO} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.example.common_grpc.OfferDTO.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getHotelid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getHotelname();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getHotelstars();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getRoomid();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getAgencyid();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getAgencyname();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getCapacity();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getPercentage();
  if (f !== 0.0) {
    writer.writeDouble(
      9,
      f
    );
  }
  f = message.getNewprice();
  if (f !== 0.0) {
    writer.writeDouble(
      10,
      f
    );
  }
  f = message.getRoomimageurlsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.org.example.common_grpc.OfferDTO.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.org.example.common_grpc.OfferDTO} returns this
 */
proto.org.example.common_grpc.OfferDTO.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 hotelId = 2;
 * @return {number}
 */
proto.org.example.common_grpc.OfferDTO.prototype.getHotelid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.org.example.common_grpc.OfferDTO} returns this
 */
proto.org.example.common_grpc.OfferDTO.prototype.setHotelid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string hotelName = 3;
 * @return {string}
 */
proto.org.example.common_grpc.OfferDTO.prototype.getHotelname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.org.example.common_grpc.OfferDTO} returns this
 */
proto.org.example.common_grpc.OfferDTO.prototype.setHotelname = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 hotelStars = 4;
 * @return {number}
 */
proto.org.example.common_grpc.OfferDTO.prototype.getHotelstars = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.org.example.common_grpc.OfferDTO} returns this
 */
proto.org.example.common_grpc.OfferDTO.prototype.setHotelstars = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 roomId = 5;
 * @return {number}
 */
proto.org.example.common_grpc.OfferDTO.prototype.getRoomid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.org.example.common_grpc.OfferDTO} returns this
 */
proto.org.example.common_grpc.OfferDTO.prototype.setRoomid = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 agencyId = 6;
 * @return {number}
 */
proto.org.example.common_grpc.OfferDTO.prototype.getAgencyid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.org.example.common_grpc.OfferDTO} returns this
 */
proto.org.example.common_grpc.OfferDTO.prototype.setAgencyid = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional string agencyName = 7;
 * @return {string}
 */
proto.org.example.common_grpc.OfferDTO.prototype.getAgencyname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.org.example.common_grpc.OfferDTO} returns this
 */
proto.org.example.common_grpc.OfferDTO.prototype.setAgencyname = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional int32 capacity = 8;
 * @return {number}
 */
proto.org.example.common_grpc.OfferDTO.prototype.getCapacity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.org.example.common_grpc.OfferDTO} returns this
 */
proto.org.example.common_grpc.OfferDTO.prototype.setCapacity = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional double percentage = 9;
 * @return {number}
 */
proto.org.example.common_grpc.OfferDTO.prototype.getPercentage = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.org.example.common_grpc.OfferDTO} returns this
 */
proto.org.example.common_grpc.OfferDTO.prototype.setPercentage = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * optional double newPrice = 10;
 * @return {number}
 */
proto.org.example.common_grpc.OfferDTO.prototype.getNewprice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.org.example.common_grpc.OfferDTO} returns this
 */
proto.org.example.common_grpc.OfferDTO.prototype.setNewprice = function(value) {
  return jspb.Message.setProto3FloatField(this, 10, value);
};


/**
 * repeated string roomImageUrls = 11;
 * @return {!Array<string>}
 */
proto.org.example.common_grpc.OfferDTO.prototype.getRoomimageurlsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.org.example.common_grpc.OfferDTO} returns this
 */
proto.org.example.common_grpc.OfferDTO.prototype.setRoomimageurlsList = function(value) {
  return jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.org.example.common_grpc.OfferDTO} returns this
 */
proto.org.example.common_grpc.OfferDTO.prototype.addRoomimageurls = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.org.example.common_grpc.OfferDTO} returns this
 */
proto.org.example.common_grpc.OfferDTO.prototype.clearRoomimageurlsList = function() {
  return this.setRoomimageurlsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.org.example.common_grpc.AgencyOfferRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.org.example.common_grpc.AgencyOfferRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.example.common_grpc.AgencyOfferRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    agencyid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    agencylogin: jspb.Message.getFieldWithDefault(msg, 2, ""),
    agencypassword: jspb.Message.getFieldWithDefault(msg, 3, ""),
    city: jspb.Message.getFieldWithDefault(msg, 4, ""),
    stars: jspb.Message.getFieldWithDefault(msg, 5, 0),
    category: jspb.Message.getFieldWithDefault(msg, 6, ""),
    capacity: jspb.Message.getFieldWithDefault(msg, 7, 0),
    start: jspb.Message.getFieldWithDefault(msg, 8, ""),
    end: jspb.Message.getFieldWithDefault(msg, 9, ""),
    maxprice: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.org.example.common_grpc.AgencyOfferRequest}
 */
proto.org.example.common_grpc.AgencyOfferRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.org.example.common_grpc.AgencyOfferRequest;
  return proto.org.example.common_grpc.AgencyOfferRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.org.example.common_grpc.AgencyOfferRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.org.example.common_grpc.AgencyOfferRequest}
 */
proto.org.example.common_grpc.AgencyOfferRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAgencyid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAgencylogin(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAgencypassword(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCity(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStars(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategory(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCapacity(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setStart(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setEnd(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMaxprice(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.org.example.common_grpc.AgencyOfferRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.org.example.common_grpc.AgencyOfferRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.example.common_grpc.AgencyOfferRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAgencyid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getAgencylogin();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAgencypassword();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCity();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getStars();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getCategory();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCapacity();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getStart();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getEnd();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getMaxprice();
  if (f !== 0.0) {
    writer.writeDouble(
      10,
      f
    );
  }
};


/**
 * optional int32 agencyId = 1;
 * @return {number}
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.getAgencyid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.org.example.common_grpc.AgencyOfferRequest} returns this
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.setAgencyid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string agencyLogin = 2;
 * @return {string}
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.getAgencylogin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.org.example.common_grpc.AgencyOfferRequest} returns this
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.setAgencylogin = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string agencyPassword = 3;
 * @return {string}
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.getAgencypassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.org.example.common_grpc.AgencyOfferRequest} returns this
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.setAgencypassword = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string city = 4;
 * @return {string}
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.getCity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.org.example.common_grpc.AgencyOfferRequest} returns this
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.setCity = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 stars = 5;
 * @return {number}
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.getStars = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.org.example.common_grpc.AgencyOfferRequest} returns this
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.setStars = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string category = 6;
 * @return {string}
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.getCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.org.example.common_grpc.AgencyOfferRequest} returns this
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.setCategory = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int32 capacity = 7;
 * @return {number}
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.getCapacity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.org.example.common_grpc.AgencyOfferRequest} returns this
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.setCapacity = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional string start = 8;
 * @return {string}
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.getStart = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.org.example.common_grpc.AgencyOfferRequest} returns this
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.setStart = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string end = 9;
 * @return {string}
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.getEnd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.org.example.common_grpc.AgencyOfferRequest} returns this
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.setEnd = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional double maxPrice = 10;
 * @return {number}
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.getMaxprice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.org.example.common_grpc.AgencyOfferRequest} returns this
 */
proto.org.example.common_grpc.AgencyOfferRequest.prototype.setMaxprice = function(value) {
  return jspb.Message.setProto3FloatField(this, 10, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.org.example.common_grpc.AgencyOfferResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.org.example.common_grpc.AgencyOfferResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.org.example.common_grpc.AgencyOfferResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.org.example.common_grpc.AgencyOfferResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.example.common_grpc.AgencyOfferResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    offersList: jspb.Message.toObjectList(msg.getOffersList(),
    proto.org.example.common_grpc.OfferDTO.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.org.example.common_grpc.AgencyOfferResponse}
 */
proto.org.example.common_grpc.AgencyOfferResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.org.example.common_grpc.AgencyOfferResponse;
  return proto.org.example.common_grpc.AgencyOfferResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.org.example.common_grpc.AgencyOfferResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.org.example.common_grpc.AgencyOfferResponse}
 */
proto.org.example.common_grpc.AgencyOfferResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.org.example.common_grpc.OfferDTO;
      reader.readMessage(value,proto.org.example.common_grpc.OfferDTO.deserializeBinaryFromReader);
      msg.addOffers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.org.example.common_grpc.AgencyOfferResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.org.example.common_grpc.AgencyOfferResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.org.example.common_grpc.AgencyOfferResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.org.example.common_grpc.AgencyOfferResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOffersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.org.example.common_grpc.OfferDTO.serializeBinaryToWriter
    );
  }
};


/**
 * repeated OfferDTO offers = 1;
 * @return {!Array<!proto.org.example.common_grpc.OfferDTO>}
 */
proto.org.example.common_grpc.AgencyOfferResponse.prototype.getOffersList = function() {
  return /** @type{!Array<!proto.org.example.common_grpc.OfferDTO>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.org.example.common_grpc.OfferDTO, 1));
};


/**
 * @param {!Array<!proto.org.example.common_grpc.OfferDTO>} value
 * @return {!proto.org.example.common_grpc.AgencyOfferResponse} returns this
*/
proto.org.example.common_grpc.AgencyOfferResponse.prototype.setOffersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.org.example.common_grpc.OfferDTO=} opt_value
 * @param {number=} opt_index
 * @return {!proto.org.example.common_grpc.OfferDTO}
 */
proto.org.example.common_grpc.AgencyOfferResponse.prototype.addOffers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.org.example.common_grpc.OfferDTO, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.org.example.common_grpc.AgencyOfferResponse} returns this
 */
proto.org.example.common_grpc.AgencyOfferResponse.prototype.clearOffersList = function() {
  return this.setOffersList([]);
};


goog.object.extend(exports, proto.org.example.common_grpc);
